apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: myhttp
      app.kubernetes.io/component: myhttp
      app.kubernetes.io/instance: myhttp
    name: myhttp
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/murill00/my_httpd
      from:
        kind: DockerImage
        name: quay.io/murill00/my_httpd
      generation: null
      importPolicy:
        importMode: Legacy
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"myhttp:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"myhttp\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: myhttp
      app.kubernetes.io/component: myhttp
      app.kubernetes.io/instance: myhttp
    name: myhttp
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: myhttp
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: myhttp
      spec:
        containers:
        - image: ' '
          name: myhttp
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: myhttp
      app.kubernetes.io/component: myhttp
      app.kubernetes.io/instance: myhttp
    name: myhttp
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deployment: myhttp
  status:
    loadBalancer: {}
kind: List
metadata: {}
